# Production Configuration
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
services:
  customer:
    url: ${CUSTOMER_SERVICE_URL:http://customer-service:8081}
  corebanking:
    url: ${COREBANKING_SERVICE_URL:http://corebanking-service:8082}
  deeplink:
    url: ${DEEPLINK_SERVICE_URL:http://deeplink-service:8083}
  lmps:
    url: ${LMPS_SERVICE_URL:http://lmps-service:8084}

logging:
  level:
    root: WARN
    com.lbb: INFO